name: Run Script

on: 
  workflow_dispatch:
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]

jobs:
  debug_context:
    runs-on: ubuntu-latest
    steps:
      - name: Dump entire GitHub context
        run: echo "${{ toJSON(github) }}"

  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Run Python script # works fro all platforms ( linux, windows, macos )
        uses: jannekem/run-python-script-action@v1
        with:
          script: |
            import os
            print("Directory contents:")
            for f in os.listdir():
                print(f)

      - name: Run Python script  # works for linux only
        run: |
          python - <<EOF
          import os
          print("Directory contents:")
          for f in os.listdir():
              print(f)
          EOF

  test_muilple_platforms:
    needs: build
    
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]    # these are ran in parallel
        python-version: ['3.10', '3.11', '3.12', '3.13'] 
        # these combinations will be tested in parallel
        # Ubuntu + Python 3.10, ubuntu + Python 3.11, Ubuntu + Python 3.12, Ubuntu + Python 3.13,
        # Windows + Python 3.10, Windows + Python 3.11, Windows + Python 3.12, Windows + Python 3.13

    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Get code
        uses: actions/checkout@v6

      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run Python script # works for all platfroms ( linux, windows, macos )
        run: |
          python -c "import os; print('Directory contents:'); [print(f) for f in os.listdir()]"
